/* Connections map — how each class comes together end to end */
window.LMA_CLASSMAPS = [
  {
    id: 'property-df',
    icon: '🏭',
    name: 'Property D&F',
    intro: 'A large industrial property programme — say a mining group with US$600m of assets and heavy business-interruption exposure in an earthquake zone.',
    stages: [
      { icon: '🏭', title: 'The client and the risk',
        desc: 'A mining group needs cover for plants, machinery and lost profits. Total insured values, construction, occupancy, protection and location (the “COPE” data) plus survey reports define the risk.',
        links: ['classes1/property-df'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'Its local broker cannot place US$600m domestically, so a London wholesale broker structures the programme in layers and takes it to the subscription market with, say, a 75% order.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'A specialist property lead prices the layers off engineering data and a catastrophe model; followers subscribe. Written lines exceed 100% and are signed down pro rata.',
        links: ['market/placement', 'premium/subscription-maths'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium flows through central settlement, less brokerage. It earns over the policy year — with catastrophe-season shape if exposure is seasonal — and adjusts if declared values change.',
        links: ['premium/waterfall', 'premium/earning'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Each carrier logs the risk against its earthquake-zone aggregate, feeds it into the catastrophe model, and checks the portfolio still sits inside its 1-in-100 appetite and Lloyd’s scenario tolerances.',
        links: ['exposure/cat-models', 'exposure/rds'] },
      { icon: '🏦', title: 'Capital',
        desc: 'The new exposure raises modelled catastrophe risk, which flows into the syndicate’s one-in-200 requirement and, with the 35% uplift, into members’ Funds at Lloyd’s.',
        links: ['capital/lloyds-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'The carrier’s per-risk excess of loss caps any single large fire loss; its catastrophe tower caps the earthquake event; co-participations and reinstatements shape the net.',
        links: ['reinsurance/xol'] },
      { icon: '📋', title: 'The loss',
        desc: 'An earthquake damages the plant. Loss adjusters quantify damage and months of business interruption; the lead and second agreement party agree the claim; every carrier pays its signed line and books recoveries.',
        links: ['claims/claims-process'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Short tail: most of the ultimate is known within a year or two, though contingent business-interruption strands emerge late. The event feeds back into model validation — and property rates harden at renewal.',
        links: ['claims/ibnr', 'pricing/cycle'] }
    ]
  },
  {
    id: 'cat-treaty',
    icon: '🌀',
    name: 'Property treaty',
    intro: 'A catastrophe excess-of-loss treaty protecting a Florida-focused insurer — London writing reinsurance as a business line.',
    stages: [
      { icon: '🌀', title: 'The client and the risk',
        desc: 'The client is itself an insurer: a Florida carrier with two million policies wanting protection above its retention for hurricane events. Its exposure data and model outputs are the underwriting raw material.',
        links: ['classes1/terror-cat'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A reinsurance broker structures the programme — layers, retentions, reinstatements — and markets it to London, Bermuda and Europe. Broker analytics teams supply modelling both ways.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'A respected treaty lead sets the rate on line for each layer; followers take shares. The same subscription mechanics apply — one slip, several markets, several liability.',
        links: ['market/placement', 'pricing/rate-on-line'] },
      { icon: '💷', title: 'Premium',
        desc: 'Treaty premium is often paid in instalments, with reinstatement premiums falling due when events consume limit — premium that arrives precisely because losses did.',
        links: ['premium/estimates'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'The reinsurer aggregates this cedant’s Florida exposure with every other treaty it writes: its own exceedance-probability curve and peak-zone limits decide whether the line fits.',
        links: ['exposure/cat-models'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Peak-zone catastrophe risk usually dominates the tail of the capital model — this class often receives the largest co-measure allocation and drives the one-in-200.',
        links: ['advanced/capital-allocation'] },
      { icon: '🛡️', title: 'Outwards: retrocession',
        desc: 'The reinsurer protects itself in the retrocession market — often with collateralised capacity and catastrophe bonds, whose trapped-collateral dynamics amplify the market cycle.',
        links: ['mga/ils'] },
      { icon: '📋', title: 'The loss',
        desc: 'A major hurricane: the cedant aggregates thousands of claims into an event loss under the hours clause; the treaty pays above the attachment; reinstatement premium restores the limit for a second storm.',
        links: ['reinsurance/xol'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Event reserving starts from model estimates and refines as the cedant reports. A big year hardens rates across the whole market — losses travel up the chain, repricing travels down.',
        links: ['pricing/cycle'] }
    ]
  },
  {
    id: 'marine-cargo',
    icon: '🚢',
    name: 'Marine cargo',
    intro: 'A global commodity trader’s cargo programme — thousands of shipments a year, insured warehouse to warehouse.',
    stages: [
      { icon: '🚢', title: 'The client and the risk',
        desc: 'A trader moves grain, metals and fuels across hundreds of voyages. Cover follows the goods door to door — at sea, in port, in warehouses — with general-average contributions included.',
        links: ['classes1/marine'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A marine broker places an open cover: rates agreed per commodity and route, with the year’s premium based on estimated shipment values declared as they happen.',
        links: ['premium/estimates'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'A cargo lead sets terms; followers line the slip. High-volume cargo also flows through binders and lineslips, with coverholders issuing certificates per shipment.',
        links: ['market/delegated'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium is an estimate trued up by declarations — a minimum and deposit protects the insurer if volumes fall short. Earnings track shipping activity through the year.',
        links: ['premium/estimates'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'The hidden accumulation is static: cargo from thousands of policies piles up in the same ports and warehouses. Port-aggregate monitoring is the class’s Tianjin lesson.',
        links: ['exposure/why-exposure'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Attritional cargo losses are stable, so capital consumption is modest — until port accumulations or systemic events enter the tail. Diversifying classes like this earn favourable allocations.',
        links: ['capital/diversification'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'A risk excess protects against any single large shipment loss; catastrophe cover responds to port events; proportional treaties support binder volumes.',
        links: ['reinsurance/proportional'] },
      { icon: '📋', title: 'The loss',
        desc: 'A vessel grounds and salvage is declared general average: the trader’s cargo insurer pays its contribution — a claim with no damage to the goods at all — computed by average adjusters, sometimes over years.',
        links: ['classes1/marine'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Mostly short tail and attritional — priced on experience — but general-average and port-event strands develop slowly. Binder premium earns over up to 24 months.',
        links: ['premium/earning', 'pricing/rating-methods'] }
    ]
  },
  {
    id: 'energy',
    icon: '🛢️',
    name: 'Upstream energy',
    intro: 'An offshore platform package — physical damage, control of well and liability for an operator in the Gulf of Mexico.',
    stages: [
      { icon: '🛢️', title: 'The client and the risk',
        desc: 'An operator insures a US$1.2bn platform, the cost of regaining control of a blowout, and pollution liability — three covers in one package slip, in a hurricane path.',
        links: ['classes1/energy'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A specialist energy broker packages the risk with engineering reports, drilling schedules and loss records, and brings it to the handful of markets with real upstream expertise.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'An energy lead scrutinises well design and process safety, prices each section, and writes the first line; the slip fills across London and international markets, signed down if oversubscribed.',
        links: ['market/placement'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium volume tracks oil prices — more drilling, higher values, richer business-interruption exposure. Package sections earn on different patterns.',
        links: ['premium/earning'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'The platform enters both the single-risk ledger (one enormous probable maximum loss) and the Gulf hurricane aggregate; the two views bind different appetites.',
        links: ['exposure/why-exposure'] },
      { icon: '🏦', title: 'Capital',
        desc: 'A single risk this size consumes real capital: its worst case (platform loss plus blowout plus pollution in one event) sits visibly in the firm’s tail scenarios.',
        links: ['capital/why-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Facultative protection is common on outsize platforms, alongside the energy account’s risk excess and the catastrophe tower for hurricane season.',
        links: ['reinsurance/why-ri'] },
      { icon: '📋', title: 'The loss',
        desc: 'A blowout: topside damage, well-kill and redrilling costs, pollution claims — three sections of one package respond, with specialist adjusters quantifying each strand.',
        links: ['classes1/energy', 'claims/claims-process'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Physical damage settles in a couple of years; pollution liability can run far longer. Big energy losses reprice the whole class — capacity is concentrated and memories are shared.',
        links: ['claims/ibnr', 'pricing/cycle'] }
    ]
  },
  {
    id: 'aviation',
    icon: '✈️',
    name: 'Airline',
    intro: 'A flag carrier’s hull and liability programme — US$4bn of fleet, US$2bn of liability limit, and the market’s vertical-placement quirk.',
    stages: [
      { icon: '✈️', title: 'The client and the risk',
        desc: 'An airline insures its fleet (hull) and, far larger, its liability to passengers and third parties. War and allied perils are placed separately with 7-day cancellation notice.',
        links: ['classes1/aviation'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'One of a small number of specialist aviation brokers runs the renewal — fleet data, passenger volumes, loss record, jurisdiction analysis — against a compact global market.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: vertical',
        desc: 'Aviation’s idiosyncrasy: carriers on the same slip may write at different rates, each negotiating its own terms. Shares still sum to 100%, but there is no single market price.',
        links: ['classes1/aviation'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium is small against limits — the whole world’s airline premium roughly equals two major widebody losses — so discipline erodes fast when capacity is plentiful.',
        links: ['pricing/ratios'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Accumulation is people and metal in one place: two insured aircraft colliding, one airport event, war seizing a leased fleet across one country — scenario-tested rather than modelled.',
        links: ['exposure/rds'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Severity-driven and litigation-tailed: liability settlements develop over years in United States courts, holding capital long after the flight year ends.',
        links: ['capital/why-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Event excess of loss protects against the major crash; market-level protections respond to multi-policy events like the leasing disputes after 2022.',
        links: ['reinsurance/xol'] },
      { icon: '📋', title: 'The loss',
        desc: 'A widebody loss: hull pays agreed value quickly; liability unfolds through international conventions and litigation for years, with the lead managing the market’s claim.',
        links: ['claims/claims-process'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Hull is short tail; liability is long. One disaster consumes decades of an airline’s premium — the class prices the market-wide disaster rate, not any single airline’s history.',
        links: ['claims/ibnr', 'pricing/rating-methods'] }
    ]
  },
  {
    id: 'casualty',
    icon: '⚖️',
    name: 'US excess casualty',
    intro: 'A US$15m xs US$35m layer on a US industrial company’s liability tower — the long-tail heartland.',
    stages: [
      { icon: '⚖️', title: 'The client and the risk',
        desc: 'A US manufacturer buys a liability tower against injury and product claims. Jurisdiction is the rating factor: the same accident costs multiples more in a US courtroom.',
        links: ['classes2/casualty'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'The US retail broker builds the tower; London sees the excess layers via wholesale brokers — the classic role for London capacity in US casualty programmes.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'Each layer is priced from ground-up expectations via increased limit factors; occurrence triggers mean the policy answers for injuries during the period whenever claims arrive.',
        links: ['advanced/layer-pricing', 'pricing/terms'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium earns over the policy year, but the risk period truly ends only when the last claim settles — perhaps decades later. Rate change versus claims inflation is the metric that matters.',
        links: ['pricing/rating-methods'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Accumulation is causal, not geographic: one harmful product or substance touching thousands of insureds across many policy years. Horizon-scanning hunts the next asbestos.',
        links: ['exposure/clash'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Reserve risk dominates: the one-year capital charge recurs every year until the tail runs off, and social inflation can move a decade of reserves at once.',
        links: ['advanced/capital-allocation'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Excess-of-loss protections cap severity, clash covers respond when one event hits several policies, and adverse development covers can cap the back years.',
        links: ['reinsurance/xol', 'bespoke/retrospective'] },
      { icon: '📋', title: 'The loss',
        desc: 'A products claim surfaces years after the policy period, reserved at US$4m and settling at the full US$15m limit six years later — late arrival, slow adverse development.',
        links: ['classes2/casualty'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Incurred-but-not-reported dwarfs case reserves for young years; Bornhuetter–Ferguson holds the line until data matures. Reserving humility is the class’s survival trait.',
        links: ['claims/bf-method', 'advanced/reserving-diagnostics'] }
    ]
  },
  {
    id: 'cyber',
    icon: '💻',
    name: 'Cyber',
    intro: 'A retailer’s cyber programme — ransomware response, business interruption and privacy liability, with systemic risk overhead.',
    stages: [
      { icon: '💻', title: 'The client and the risk',
        desc: 'A retailer holding millions of customer records buys first-party crisis cover, systems business interruption and privacy liability. Its security controls are the underwriting submission.',
        links: ['classes2/cyber'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'The broker markets the risk on control quality — multi-factor authentication, tested offline backups, patching — because without the basics there is no quote at all.',
        links: ['classes2/cyber'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'A cyber lead sets terms including the war/state-actor exclusion wording — the class’s most contested clause since NotPetya — and followers subscribe the tower.',
        links: ['market/placement'] },
      { icon: '💷', title: 'Premium',
        desc: 'The class repriced violently through the ransomware epidemic — rates tripling, then stabilising: the fastest full market cycle in living memory.',
        links: ['pricing/cycle'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Accumulation is a shared dependency, not a shared postcode: one cloud provider or software vulnerability touching thousands of insureds at once. Silent-cyber wording remediation polices the leakage.',
        links: ['exposure/clash'] },
      { icon: '🏦', title: 'Capital',
        desc: 'The systemic scenario — one event correlating the whole book — caps prudent aggregate and drives the capital charge. There is no geography to diversify across.',
        links: ['capital/why-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Quota shares support growth in a young class; aggregate covers and emerging cyber-catastrophe structures address the systemic tail.',
        links: ['reinsurance/programme'] },
      { icon: '📋', title: 'The loss',
        desc: 'Ransomware strikes: the insurer’s response panel runs the first 72 hours — forensics, legal, notification — then pays business interruption and any privacy claims. The product is a service as much as an indemnity.',
        links: ['classes2/cyber'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Incident costs settle quickly; privacy litigation takes longer. Renewal underwriting feeds back loss lessons as required controls — underwriting and loss prevention fused.',
        links: ['claims/ibnr'] }
    ]
  },
  {
    id: 'political-credit',
    icon: '🌍',
    name: 'Political risk & credit',
    intro: 'A bank’s protection on emerging-market lending — insurance competing with capital markets, underwritten like applied geopolitics.',
    stages: [
      { icon: '🌍', title: 'The client and the risk',
        desc: 'A bank finances commodity exports from a frontier market and wants protection against the buyer defaulting or the government blocking payment — credit and political perils intertwined.',
        links: ['classes2/political-credit'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A specialist broker structures the deal: insured percentage (the bank retains a slice), waiting period, tenor matched to the loan — wordings negotiated against banking regulation.',
        links: ['bespoke/credit-enhancement'] },
      { icon: '✍️', title: 'Placement: syndication',
        desc: 'The lead underwrites obligor, country and structure; large deals syndicate across the small community of credit and political-risk markets — subscription reborn as deal syndication.',
        links: ['bespoke/deal-lifecycle'] },
      { icon: '💷', title: 'Premium',
        desc: 'Multi-year premium follows the loan’s life, often paid annually in advance; earning matches the exposure profile as the loan amortises.',
        links: ['premium/earning'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Aggregation runs by obligor and country, not postcode: one sovereign crisis or corporate collapse can hit dozens of policies. Country limits are the binding budget.',
        links: ['classes2/political-credit'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Credit risks cluster in recessions — wrong-way risk — so diversification credit against catastrophe books is real, but against other credit exposures much less so.',
        links: ['bespoke/credit-enhancement'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Whole-account treaties protect the credit book; hybrid deals need careful checking that class-based treaty wordings actually pick them up.',
        links: ['bespoke/deal-lifecycle'] },
      { icon: '📋', title: 'The loss',
        desc: 'The buyer defaults amid a currency crisis. After the 180-day waiting period filters delay from default, the insurer pays its share — then spends years pursuing recoveries in the restructuring.',
        links: ['classes2/political-credit'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Ultimate cost depends on recoveries as much as the default itself: net loss ratios turn on restructuring skill. The class’s cycle follows the global credit cycle, not the hurricane season.',
        links: ['claims/ibnr'] }
    ]
  },
  {
    id: 'binder',
    icon: '📋',
    name: 'Binder programme',
    intro: 'A delegated-authority binder — 4,000 small US commercial property policies written by a coverholder on a syndicate’s behalf. Around a third of Lloyd’s premium arrives this way.',
    stages: [
      { icon: '🏪', title: 'The clients — thousands of them',
        desc: 'Shops, workshops and offices, each too small for open-market placement individually — but in aggregate exactly the business London wants.',
        num: '4,000 policies · average premium US$6,000 · US$24m a year',
        links: ['market/delegated'] },
      { icon: '🖊️', title: 'The coverholder',
        desc: 'A Texas managing general agent holds the pen: it quotes, binds and issues documents within the binder’s rules — maximum line, excluded coastal counties, rating floors.',
        num: 'Coverholder commission 22% of gross premium',
        links: ['market/delegated'] },
      { icon: '✍️', title: 'Placing the binder itself',
        desc: 'The real underwriting decision: a London broker places the binding authority with a lead syndicate and followers. The carriers are underwriting the coverholder — its controls, its track record — not the 4,000 risks.',
        num: 'Binder cap US$25m of annual premium',
        links: ['market/placement'] },
      { icon: '💷', title: 'Premium via bordereaux',
        desc: 'Monthly bordereaux report what was bound; premium is an estimate trued up as declarations arrive, and a policy attaching in month 12 runs to month 24 — the binder’s long earning tail.',
        num: 'Estimated premium US$24m, earning over up to 24 months',
        links: ['premium/earning', 'premium/estimates'] },
      { icon: '🌪️', title: 'Exposure management from data',
        desc: 'The carriers never saw the risks before binding — bordereau data quality IS exposure management: geocoding every location into wind and quake aggregates, policing the coastal exclusions.',
        num: 'Zone aggregate tracked monthly against a US$60m budget',
        links: ['exposure/why-exposure'] },
      { icon: '🏦', title: 'Capital',
        desc: 'The binder book enters the syndicate plan and internal model like any class — but with an extra operational-risk flavour: coverholder failure and data error are real capital considerations.',
        links: ['capital/lloyds-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'A risk excess protects against the largest single insured; the catastrophe tower responds if a windstorm sweeps a concentration the exclusions missed.',
        links: ['reinsurance/xol'] },
      { icon: '📋', title: 'Claims — also delegated',
        desc: 'A third-party administrator settles small claims under delegated claims authority, reported via claims bordereaux; larger losses escalate to the lead syndicate’s claims team.',
        num: 'Claims authority: TPA settles up to US$50,000 per claim',
        links: ['claims/claims-process'] },
      { icon: '📊', title: 'Reserving, audit and profit commission',
        desc: 'Binder-year triangles develop late (that 24-month earning). Annual on-site audits verify the bordereaux; if the account beats its target loss ratio, the coverholder earns profit commission — alignment in action.',
        num: 'Profit commission: 15% of profit below a 65% loss ratio',
        links: ['claims/triangles', 'regulation/conduct'] }
    ]
  },
  {
    id: 'dno',
    icon: '🏢',
    name: 'Directors’ & officers’',
    intro: 'A US-listed technology company’s directors’ & officers’ tower — claims-made cover where the catastrophe is a share-price collapse, not a storm.',
    stages: [
      { icon: '🏢', title: 'The client and the risk',
        desc: 'The company’s directors face personal liability for alleged mismanagement — above all US securities class actions after a share-price fall. The tower protects them (and reimburses the company).',
        num: 'Tower: US$100m of limit above a US$5m retention',
        links: ['classes2/financial-lines'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A management-liability specialist broker structures primary plus excess layers and markets them to London and US carriers, with the company’s financials and litigation history as the submission.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: a tower of layers',
        desc: 'A primary carrier sets the wording; excess layers stack above at decreasing prices — increased-limit-factor logic in action. The trigger is claims-made: only claims first made this period count.',
        num: 'Primary US$10m at US$1.2m; top layers under US$300k per US$10m',
        links: ['advanced/layer-pricing', 'pricing/terms'] },
      { icon: '💷', title: 'Premium and the cycle',
        desc: 'Financial-lines pricing swings hard: rates doubled in the 2019–21 hardening, then fell steeply as capacity returned — a compressed lesson in the underwriting cycle.',
        links: ['pricing/cycle'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Accumulation is macroeconomic: a market crash or sector scandal hits many insureds at once. The portfolio is monitored by sector, listing exchange and layer attachment.',
        links: ['exposure/clash'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Severity-driven with an economic-cycle tail: the capital model’s bad years for this book are recessions and crises — partially correlated with the investment portfolio, a wrong-way flavour.',
        links: ['capital/diversification'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Variable quota shares support the financial-lines account; excess protections cap the largest towers where the carrier writes multiple layers of one insured.',
        links: ['reinsurance/proportional'] },
      { icon: '📋', title: 'The claim: a securities class action',
        desc: 'The share price halves on a profit warning; shareholders sue. Defence costs erode the limit from day one, and settlement discussions run for years — with each layer consumed in order.',
        num: 'Defence US$12m + settlement US$48m = US$60m into the tower',
        links: ['classes2/financial-lines'] },
      { icon: '📊', title: 'Reserving and feedback',
        desc: 'Claims-made means the universe of claims is known soon after expiry — but severity develops through litigation for years. Circumstance notifications pin emerging problems to the right policy year.',
        links: ['claims/ibnr'] }
    ]
  },
  {
    id: 'terrorism',
    icon: '💥',
    name: 'Terrorism & political violence',
    intro: 'A standalone terrorism programme on a capital-city office tower — a class where the accumulation unit is a city block and the state is part of the market.',
    stages: [
      { icon: '🏙️', title: 'The client and the risk',
        desc: 'After September 11, terrorism was excluded from standard property policies; the owner of a prime office tower buys it back standalone — property damage and business interruption from attack.',
        num: 'Values: US$700m building + US$200m business interruption',
        links: ['classes1/terror-cat'] },
      { icon: '🤝', title: 'The broking chain and the state option',
        desc: 'The broker weighs the private market against the government-backed scheme (in the United Kingdom, Pool Re). What the state scheme covers dictates what the private market sells around it.',
        links: ['classes1/terror-cat'] },
      { icon: '✍️', title: 'Placement',
        desc: 'A political-violence lead prices the risk on location above all: the same building is a different risk two streets away. Cover can extend up the spectrum — sabotage, riots, insurrection, war on land.',
        links: ['market/placement'] },
      { icon: '💷', title: 'Premium',
        desc: 'Rates are low against the values — until an event. Riot waves (Chile, South Africa) turned the strikes-and-civil-commotion end of the class loss-making and repriced it market-wide.',
        links: ['pricing/cycle'] },
      { icon: '🌪️', title: 'Exposure: the blast radius',
        desc: 'The accumulation unit is a city block: every insured value within a bomb’s damage radius aggregates. Prime districts have finite capacity, tracked address by address.',
        num: 'Carrier’s aggregate within 500m: US$900m against a US$250m scenario budget',
        links: ['exposure/why-exposure'] },
      { icon: '🏦', title: 'Capital',
        desc: 'The city-centre scenario sits alongside natural catastrophes in the internal model and the market’s prescribed disaster scenarios — one deterministic bomb, computed gross and net.',
        links: ['exposure/rds'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Political-violence catastrophe excess of loss responds per event — and the event definition (how many hours, what proximity, one cause or many?) is the clause fortunes turn on.',
        links: ['reinsurance/xol'] },
      { icon: '📋', title: 'The event',
        desc: 'A vehicle bomb damages the tower and closes the district for months: property damage plus long business interruption. Whether unrest is “terrorism”, “riot” or “insurrection” decides which policies respond — definitions are the claim.',
        num: 'Loss: US$180m damage + US$90m business interruption',
        links: ['claims/claims-process'] },
      { icon: '📊', title: 'Reserving and repricing',
        desc: 'Physical damage settles in a year or two; business-interruption and definition disputes run longer. Capacity in the affected district vanishes at renewal — the cycle at its most local.',
        links: ['pricing/cycle'] }
    ]
  },
  {
    id: 'journey-premium',
    icon: '💷',
    name: 'The premium pound',
    group: 'journey',
    intro: 'Follow £1.00 of premium from the client’s bank account to distributed profit — the whole course compressed into one pound coin.',
    stages: [
      { icon: '🏭', title: 'The client pays',
        desc: 'The insured pays the full contract price (plus any insurance premium tax, collected for the authorities on top). The clock starts: payment terms give 60–90 days for the money to move.',
        num: '£1.00 leaves the client',
        links: ['premium/cash'] },
      { icon: '🤝', title: 'Brokerage comes off the top',
        desc: 'The broker deducts its remuneration before the insurer sees the money — the first and largest slice of the waterfall.',
        num: '− 15p brokerage → 85p reaches the insurer',
        links: ['premium/waterfall'] },
      { icon: '🏛️', title: 'Through the bureau',
        desc: 'The transaction is checked, given a signing number and date, and settled through central settlement — one netted movement between broker and carrier, however many risks they share.',
        num: '85p arrives via one netted settlement',
        links: ['market/back-office'] },
      { icon: '🔒', title: 'Into trust',
        desc: 'At Lloyd’s the money lands in premium trust funds — policyholders’ security, not free corporate cash. Profit only leaves when the year of account closes.',
        num: '85p held in trust for the policyholders',
        links: ['premium/cash'] },
      { icon: '🛡️', title: 'Outwards reinsurance takes its share',
        desc: 'The carrier spends part of the premium buying its own protection — quota shares, excess of loss, the catastrophe tower.',
        num: '− 12p ceded → 73p net premium',
        links: ['reinsurance/why-ri'] },
      { icon: '📉', title: 'Claims consume the biggest slice',
        desc: 'Over the following years — quickly for property, slowly for casualty — claims are paid and reserves held for the rest, net of reinsurance recoveries.',
        num: '− 50p of net claims (paid + reserved) → 23p',
        links: ['claims/ibnr'] },
      { icon: '🏢', title: 'Expenses',
        desc: 'Underwriters, actuaries, systems, rent, Lloyd’s central costs: the market’s famously high expense base takes its share.',
        num: '− 12p of administrative expenses → 11p',
        links: ['pricing/ratios'] },
      { icon: '📈', title: 'The float works meanwhile',
        desc: 'Between receipt and claim payment the money is invested. The longer the tail, the harder the pound works — insurance’s second engine.',
        num: '+ 5p of investment income → 16p',
        links: ['advanced/float-economics'] },
      { icon: '🎉', title: 'Close and distribute',
        desc: 'At 36 months the year of account closes by reinsurance to close; the result is declared and profit finally flows to the members whose capital stood behind the year.',
        num: '16p of profit distributed — a 16% margin on the pound',
        links: ['regulation/yoa-ritc'] }
    ]
  },
  {
    id: 'journey-cat',
    icon: '🌀',
    name: 'A catastrophe event',
    group: 'journey',
    intro: 'A major hurricane makes landfall in Florida. Follow the market through the twelve months after — estimate, claims, recoveries, capital and repricing.',
    stages: [
      { icon: '🌀', title: 'Day 0: landfall',
        desc: 'A category 4 hurricane crosses the Florida coast. Within hours, modelling firms publish industry loss ranges and every carrier runs the event footprint against its own portfolio.',
        num: 'Industry estimate: US$50bn insured loss',
        links: ['exposure/cat-models'] },
      { icon: '🧮', title: 'Week 1: the first estimate',
        desc: 'The catastrophe model’s footprint gives each carrier a gross estimate long before real claims arrive — the number reported to boards, Lloyd’s and markets, with wide honest uncertainty.',
        num: 'This carrier’s modelled gross loss: US$120m ± 40%',
        links: ['exposure/cat-models'] },
      { icon: '📨', title: 'Weeks 2–12: claims pour in',
        desc: 'Thousands of advices flow through brokers and bureaus; adjusters deploy; the lead agrees interim payments so insureds can start rebuilding — claims service is the product now.',
        num: 'US$45m paid on account in the first quarter',
        links: ['claims/claims-process'] },
      { icon: '🛡️', title: 'The tower responds',
        desc: 'The event pierces the carrier’s catastrophe layers; reinstatement premiums fall due to restore cover for a possible second storm — premium arriving because losses did.',
        num: 'Recoveries US$85m · reinstatement premium payable US$9m',
        links: ['reinsurance/xol'] },
      { icon: '📊', title: 'Reserving the tail',
        desc: 'Late-reported claims, demand surge (inflated rebuild costs), litigation over wordings: reserving holds incurred-but-not-reported above the visible claims for quarters to come.',
        num: 'Booked gross ultimate: US$130m (US$25m of it IBNR)',
        links: ['claims/ibnr'] },
      { icon: '🔍', title: 'Model validation',
        desc: 'Did reality land inside the model’s range? Post-event review feeds the house view of risk: vulnerability curves, storm-surge leakage, non-modelled amplification.',
        links: ['advanced2/view-of-risk'] },
      { icon: '🏦', title: 'Capital and coming into line',
        desc: 'Losses deplete syndicate funds and raise the recalculated requirement; members top up Funds at Lloyd’s at the next coming into line. The scenario returns get re-run with the new portfolio.',
        num: 'Net cost US$54m · capital top-up US$20m',
        links: ['capital/lloyds-capital'] },
      { icon: '🧊', title: 'The capital market ripple',
        desc: 'Collateral behind catastrophe bonds and collateralised reinsurance is trapped against developing losses — capacity cannot recycle just as demand for protection spikes.',
        links: ['mga/ils'] },
      { icon: '📈', title: 'Renewal: the cycle turns',
        desc: 'Depleted capacity and fresh fear reprice the market: rates on line jump at the next renewal season, and the carriers that kept powder dry write the hard market.',
        num: 'Catastrophe rates +30% at 1 January',
        links: ['pricing/cycle'] }
    ]
  },
  {
    id: 'journey-planning',
    icon: '🗓️',
    name: 'The planning year',
    group: 'journey',
    intro: 'Twelve months in the life of a syndicate’s plan — from strategy day to reinsurance to close, the loop that connects every function.',
    stages: [
      { icon: '🌱', title: 'Spring: strategy and rate outlook',
        desc: 'Where is each class in its cycle? What will rates do next year? The view formed here becomes the seed assumption of everything that follows.',
        links: ['pricing/cycle'] },
      { icon: '🧱', title: 'Summer: building the plan',
        desc: 'Class by class: premium, rate change, attritional and catastrophe loss ratios, expenses, reinsurance structure. Every pricing and exposure concept in this course lands in these rows.',
        num: 'Plan: £600m premium at a 92% combined ratio',
        links: ['advanced2/planning-cycle'] },
      { icon: '🧮', title: 'The capital run',
        desc: 'The internal model prices the plan’s risk: the one-in-200 ultimate requirement, uplifted 35%, becomes the members’ Economic Capital Assessment. The plan and the capital are one decision.',
        num: 'Requirement £200m → £270m with the uplift',
        links: ['capital/lloyds-capital'] },
      { icon: '🔍', title: 'Autumn: Lloyd’s review',
        desc: 'Central challenge on rate assumptions, loss ratios versus track record, catastrophe appetite versus tolerances. Weak plans are trimmed or their capital loaded — approval is permission to trade.',
        links: ['market/inside-lloyds'] },
      { icon: '🏦', title: 'November: coming into line',
        desc: 'Members lodge Funds at Lloyd’s to meet the assessment. No funds, no underwriting on 1 January.',
        num: '£270m of member assets in trust',
        links: ['capital/lloyds-capital'] },
      { icon: '🎬', title: '1 January: the year of account opens',
        desc: 'The new year begins writing; every policy incepting this calendar year belongs to it, and its members own the eventual result.',
        links: ['market/back-office'] },
      { icon: '📡', title: 'All year: monitoring',
        desc: 'Actual versus plan on premium and rate change; claims versus picks; catastrophe events against the aggregate budget; reinsurance actually placed versus assumed. Deviations trigger reforecasts.',
        num: 'Q1 alarm: achieved rate +1% vs +4% planned',
        links: ['advanced2/portfolio-mi'] },
      { icon: '🔧', title: 'Mid-year: reforecast and true-up',
        desc: 'The reforecast reprices the year honestly — and if the recalculated capital requirement has risen, members top up at the mid-year coming into line.',
        num: 'Combined ratio reforecast 95% · capital +£18m',
        links: ['advanced2/planning-cycle'] },
      { icon: '🏁', title: 'Month 36: close',
        desc: 'Three years on, the year of account closes by reinsurance to close: remaining liabilities transfer to the next year for a premium equal to their estimated value, and the result is finally distributed.',
        num: 'Reinsurance to close premium: £320m of transferred liabilities',
        links: ['regulation/yoa-ritc'] }
    ]
  },
  {
    id: 'journey-claim',
    icon: '⚖️',
    name: 'Life of a large claim',
    group: 'journey',
    intro: 'A refinery fire, first advice to final settlement — how a subscription market pays US$54m without falling over.',
    stages: [
      { icon: '🔥', title: 'The event',
        desc: 'A crude unit explodes and burns. The insured’s priority is safety, then recovery; its broker’s priority is triggering the programme placed two years earlier.',
        num: 'Early damage estimate: US$60m plus months of downtime',
        links: ['classes1/energy'] },
      { icon: '📨', title: 'Notification',
        desc: 'The broker advises every subscribing carrier through the market’s electronic claims file — one claim record for a twelve-carrier subscription.',
        links: ['claims/claims-process'] },
      { icon: '📌', title: 'First reserves',
        desc: 'Each carrier books a case reserve at its signed line share of the estimate — the number that flows instantly into month-end results, reinsurance projections and capital models.',
        num: 'A 7% follower reserves US$4.2m',
        links: ['claims/claims-process'] },
      { icon: '🔎', title: 'The experts',
        desc: 'The lead appoints loss adjusters; forensic accountants quantify business interruption; lawyers check coverage — was the maintenance warranty complied with? Facts before money.',
        links: ['advanced/contract-law'] },
      { icon: '💸', title: 'Interim payments',
        desc: 'Rebuilding cannot wait for final quantification: the lead agrees payments on account, and every carrier funds its share through central settlement.',
        num: 'US$20m paid on account in months 2–6',
        links: ['market/back-office'] },
      { icon: '🤝', title: 'Agreement',
        desc: 'Final quantum lands: adjusted physical damage plus business interruption over the indemnity period. The lead and second agreement party agree it, binding the whole following market.',
        num: 'Final agreed claim: US$54m',
        links: ['claims/claims-process'] },
      { icon: '🏛️', title: 'Settlement',
        desc: 'Each carrier pays its signed line of the agreed figure — several liability, one netted cash movement per carrier, releasing any over-reserve.',
        num: 'The 7% follower pays US$3.78m and releases US$0.42m',
        links: ['premium/subscription-maths'] },
      { icon: '🛡️', title: 'Recoveries',
        desc: 'Carriers whose net retentions are pierced recover from their per-risk excess of loss; outwards teams check treaty wordings pick up the loss and chase the collections.',
        num: 'One carrier recovers US$2.1m above its US$1.5m retention',
        links: ['reinsurance/ri-accounting'] },
      { icon: '📊', title: 'Closure and feedback',
        desc: 'The file closes; the loss feeds pricing (was the rate adequate?), exposure management (was the probable maximum loss right?) and the renewal negotiation. Claims are the data the next cycle is built from.',
        links: ['advanced2/portfolio-mi'] }
    ]
  }
];
