/* Connections map — how each class comes together end to end */
window.LMA_CLASSMAPS = [
  {
    id: 'property-df',
    icon: '🏭',
    name: 'Property D&F',
    intro: 'A large industrial property programme — say a mining group with US$600m of assets and heavy business-interruption exposure in an earthquake zone.',
    stages: [
      { icon: '🏭', title: 'The client and the risk',
        desc: 'A mining group needs cover for plants, machinery and lost profits. Total insured values, construction, occupancy, protection and location (the “COPE” data) plus survey reports define the risk.',
        links: ['classes1/property-df'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'Its local broker cannot place US$600m domestically, so a London wholesale broker structures the programme in layers and takes it to the subscription market with, say, a 75% order.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'A specialist property lead prices the layers off engineering data and a catastrophe model; followers subscribe. Written lines exceed 100% and are signed down pro rata.',
        links: ['market/placement', 'premium/subscription-maths'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium flows through central settlement, less brokerage. It earns over the policy year — with catastrophe-season shape if exposure is seasonal — and adjusts if declared values change.',
        links: ['premium/waterfall', 'premium/earning'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Each carrier logs the risk against its earthquake-zone aggregate, feeds it into the catastrophe model, and checks the portfolio still sits inside its 1-in-100 appetite and Lloyd’s scenario tolerances.',
        links: ['exposure/cat-models', 'exposure/rds'] },
      { icon: '🏦', title: 'Capital',
        desc: 'The new exposure raises modelled catastrophe risk, which flows into the syndicate’s one-in-200 requirement and, with the 35% uplift, into members’ Funds at Lloyd’s.',
        links: ['capital/lloyds-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'The carrier’s per-risk excess of loss caps any single large fire loss; its catastrophe tower caps the earthquake event; co-participations and reinstatements shape the net.',
        links: ['reinsurance/xol'] },
      { icon: '📋', title: 'The loss',
        desc: 'An earthquake damages the plant. Loss adjusters quantify damage and months of business interruption; the lead and second agreement party agree the claim; every carrier pays its signed line and books recoveries.',
        links: ['claims/claims-process'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Short tail: most of the ultimate is known within a year or two, though contingent business-interruption strands emerge late. The event feeds back into model validation — and property rates harden at renewal.',
        links: ['claims/ibnr', 'pricing/cycle'] }
    ]
  },
  {
    id: 'cat-treaty',
    icon: '🌀',
    name: 'Property treaty',
    intro: 'A catastrophe excess-of-loss treaty protecting a Florida-focused insurer — London writing reinsurance as a business line.',
    stages: [
      { icon: '🌀', title: 'The client and the risk',
        desc: 'The client is itself an insurer: a Florida carrier with two million policies wanting protection above its retention for hurricane events. Its exposure data and model outputs are the underwriting raw material.',
        links: ['classes1/terror-cat'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A reinsurance broker structures the programme — layers, retentions, reinstatements — and markets it to London, Bermuda and Europe. Broker analytics teams supply modelling both ways.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'A respected treaty lead sets the rate on line for each layer; followers take shares. The same subscription mechanics apply — one slip, several markets, several liability.',
        links: ['market/placement', 'pricing/rate-on-line'] },
      { icon: '💷', title: 'Premium',
        desc: 'Treaty premium is often paid in instalments, with reinstatement premiums falling due when events consume limit — premium that arrives precisely because losses did.',
        links: ['premium/estimates'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'The reinsurer aggregates this cedant’s Florida exposure with every other treaty it writes: its own exceedance-probability curve and peak-zone limits decide whether the line fits.',
        links: ['exposure/cat-models'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Peak-zone catastrophe risk usually dominates the tail of the capital model — this class often receives the largest co-measure allocation and drives the one-in-200.',
        links: ['advanced/capital-allocation'] },
      { icon: '🛡️', title: 'Outwards: retrocession',
        desc: 'The reinsurer protects itself in the retrocession market — often with collateralised capacity and catastrophe bonds, whose trapped-collateral dynamics amplify the market cycle.',
        links: ['mga/ils'] },
      { icon: '📋', title: 'The loss',
        desc: 'A major hurricane: the cedant aggregates thousands of claims into an event loss under the hours clause; the treaty pays above the attachment; reinstatement premium restores the limit for a second storm.',
        links: ['reinsurance/xol'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Event reserving starts from model estimates and refines as the cedant reports. A big year hardens rates across the whole market — losses travel up the chain, repricing travels down.',
        links: ['pricing/cycle'] }
    ]
  },
  {
    id: 'marine-cargo',
    icon: '🚢',
    name: 'Marine cargo',
    intro: 'A global commodity trader’s cargo programme — thousands of shipments a year, insured warehouse to warehouse.',
    stages: [
      { icon: '🚢', title: 'The client and the risk',
        desc: 'A trader moves grain, metals and fuels across hundreds of voyages. Cover follows the goods door to door — at sea, in port, in warehouses — with general-average contributions included.',
        links: ['classes1/marine'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A marine broker places an open cover: rates agreed per commodity and route, with the year’s premium based on estimated shipment values declared as they happen.',
        links: ['premium/estimates'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'A cargo lead sets terms; followers line the slip. High-volume cargo also flows through binders and lineslips, with coverholders issuing certificates per shipment.',
        links: ['market/delegated'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium is an estimate trued up by declarations — a minimum and deposit protects the insurer if volumes fall short. Earnings track shipping activity through the year.',
        links: ['premium/estimates'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'The hidden accumulation is static: cargo from thousands of policies piles up in the same ports and warehouses. Port-aggregate monitoring is the class’s Tianjin lesson.',
        links: ['exposure/why-exposure'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Attritional cargo losses are stable, so capital consumption is modest — until port accumulations or systemic events enter the tail. Diversifying classes like this earn favourable allocations.',
        links: ['capital/diversification'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'A risk excess protects against any single large shipment loss; catastrophe cover responds to port events; proportional treaties support binder volumes.',
        links: ['reinsurance/proportional'] },
      { icon: '📋', title: 'The loss',
        desc: 'A vessel grounds and salvage is declared general average: the trader’s cargo insurer pays its contribution — a claim with no damage to the goods at all — computed by average adjusters, sometimes over years.',
        links: ['classes1/marine'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Mostly short tail and attritional — priced on experience — but general-average and port-event strands develop slowly. Binder premium earns over up to 24 months.',
        links: ['premium/earning', 'pricing/rating-methods'] }
    ]
  },
  {
    id: 'energy',
    icon: '🛢️',
    name: 'Upstream energy',
    intro: 'An offshore platform package — physical damage, control of well and liability for an operator in the Gulf of Mexico.',
    stages: [
      { icon: '🛢️', title: 'The client and the risk',
        desc: 'An operator insures a US$1.2bn platform, the cost of regaining control of a blowout, and pollution liability — three covers in one package slip, in a hurricane path.',
        links: ['classes1/energy'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A specialist energy broker packages the risk with engineering reports, drilling schedules and loss records, and brings it to the handful of markets with real upstream expertise.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'An energy lead scrutinises well design and process safety, prices each section, and writes the first line; the slip fills across London and international markets, signed down if oversubscribed.',
        links: ['market/placement'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium volume tracks oil prices — more drilling, higher values, richer business-interruption exposure. Package sections earn on different patterns.',
        links: ['premium/earning'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'The platform enters both the single-risk ledger (one enormous probable maximum loss) and the Gulf hurricane aggregate; the two views bind different appetites.',
        links: ['exposure/why-exposure'] },
      { icon: '🏦', title: 'Capital',
        desc: 'A single risk this size consumes real capital: its worst case (platform loss plus blowout plus pollution in one event) sits visibly in the firm’s tail scenarios.',
        links: ['capital/why-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Facultative protection is common on outsize platforms, alongside the energy account’s risk excess and the catastrophe tower for hurricane season.',
        links: ['reinsurance/why-ri'] },
      { icon: '📋', title: 'The loss',
        desc: 'A blowout: topside damage, well-kill and redrilling costs, pollution claims — three sections of one package respond, with specialist adjusters quantifying each strand.',
        links: ['classes1/energy', 'claims/claims-process'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Physical damage settles in a couple of years; pollution liability can run far longer. Big energy losses reprice the whole class — capacity is concentrated and memories are shared.',
        links: ['claims/ibnr', 'pricing/cycle'] }
    ]
  },
  {
    id: 'aviation',
    icon: '✈️',
    name: 'Airline',
    intro: 'A flag carrier’s hull and liability programme — US$4bn of fleet, US$2bn of liability limit, and the market’s vertical-placement quirk.',
    stages: [
      { icon: '✈️', title: 'The client and the risk',
        desc: 'An airline insures its fleet (hull) and, far larger, its liability to passengers and third parties. War and allied perils are placed separately with 7-day cancellation notice.',
        links: ['classes1/aviation'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'One of a small number of specialist aviation brokers runs the renewal — fleet data, passenger volumes, loss record, jurisdiction analysis — against a compact global market.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: vertical',
        desc: 'Aviation’s idiosyncrasy: carriers on the same slip may write at different rates, each negotiating its own terms. Shares still sum to 100%, but there is no single market price.',
        links: ['classes1/aviation'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium is small against limits — the whole world’s airline premium roughly equals two major widebody losses — so discipline erodes fast when capacity is plentiful.',
        links: ['pricing/ratios'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Accumulation is people and metal in one place: two insured aircraft colliding, one airport event, war seizing a leased fleet across one country — scenario-tested rather than modelled.',
        links: ['exposure/rds'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Severity-driven and litigation-tailed: liability settlements develop over years in United States courts, holding capital long after the flight year ends.',
        links: ['capital/why-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Event excess of loss protects against the major crash; market-level protections respond to multi-policy events like the leasing disputes after 2022.',
        links: ['reinsurance/xol'] },
      { icon: '📋', title: 'The loss',
        desc: 'A widebody loss: hull pays agreed value quickly; liability unfolds through international conventions and litigation for years, with the lead managing the market’s claim.',
        links: ['claims/claims-process'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Hull is short tail; liability is long. One disaster consumes decades of an airline’s premium — the class prices the market-wide disaster rate, not any single airline’s history.',
        links: ['claims/ibnr', 'pricing/rating-methods'] }
    ]
  },
  {
    id: 'casualty',
    icon: '⚖️',
    name: 'US excess casualty',
    intro: 'A US$15m xs US$35m layer on a US industrial company’s liability tower — the long-tail heartland.',
    stages: [
      { icon: '⚖️', title: 'The client and the risk',
        desc: 'A US manufacturer buys a liability tower against injury and product claims. Jurisdiction is the rating factor: the same accident costs multiples more in a US courtroom.',
        links: ['classes2/casualty'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'The US retail broker builds the tower; London sees the excess layers via wholesale brokers — the classic role for London capacity in US casualty programmes.',
        links: ['market/what-is-it'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'Each layer is priced from ground-up expectations via increased limit factors; occurrence triggers mean the policy answers for injuries during the period whenever claims arrive.',
        links: ['advanced/layer-pricing', 'pricing/terms'] },
      { icon: '💷', title: 'Premium',
        desc: 'Premium earns over the policy year, but the risk period truly ends only when the last claim settles — perhaps decades later. Rate change versus claims inflation is the metric that matters.',
        links: ['pricing/rating-methods'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Accumulation is causal, not geographic: one harmful product or substance touching thousands of insureds across many policy years. Horizon-scanning hunts the next asbestos.',
        links: ['exposure/clash'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Reserve risk dominates: the one-year capital charge recurs every year until the tail runs off, and social inflation can move a decade of reserves at once.',
        links: ['advanced/capital-allocation'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Excess-of-loss protections cap severity, clash covers respond when one event hits several policies, and adverse development covers can cap the back years.',
        links: ['reinsurance/xol', 'bespoke/retrospective'] },
      { icon: '📋', title: 'The loss',
        desc: 'A products claim surfaces years after the policy period, reserved at US$4m and settling at the full US$15m limit six years later — late arrival, slow adverse development.',
        links: ['classes2/casualty'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Incurred-but-not-reported dwarfs case reserves for young years; Bornhuetter–Ferguson holds the line until data matures. Reserving humility is the class’s survival trait.',
        links: ['claims/bf-method', 'advanced/reserving-diagnostics'] }
    ]
  },
  {
    id: 'cyber',
    icon: '💻',
    name: 'Cyber',
    intro: 'A retailer’s cyber programme — ransomware response, business interruption and privacy liability, with systemic risk overhead.',
    stages: [
      { icon: '💻', title: 'The client and the risk',
        desc: 'A retailer holding millions of customer records buys first-party crisis cover, systems business interruption and privacy liability. Its security controls are the underwriting submission.',
        links: ['classes2/cyber'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'The broker markets the risk on control quality — multi-factor authentication, tested offline backups, patching — because without the basics there is no quote at all.',
        links: ['classes2/cyber'] },
      { icon: '✍️', title: 'Placement: lead and follow',
        desc: 'A cyber lead sets terms including the war/state-actor exclusion wording — the class’s most contested clause since NotPetya — and followers subscribe the tower.',
        links: ['market/placement'] },
      { icon: '💷', title: 'Premium',
        desc: 'The class repriced violently through the ransomware epidemic — rates tripling, then stabilising: the fastest full market cycle in living memory.',
        links: ['pricing/cycle'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Accumulation is a shared dependency, not a shared postcode: one cloud provider or software vulnerability touching thousands of insureds at once. Silent-cyber wording remediation polices the leakage.',
        links: ['exposure/clash'] },
      { icon: '🏦', title: 'Capital',
        desc: 'The systemic scenario — one event correlating the whole book — caps prudent aggregate and drives the capital charge. There is no geography to diversify across.',
        links: ['capital/why-capital'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Quota shares support growth in a young class; aggregate covers and emerging cyber-catastrophe structures address the systemic tail.',
        links: ['reinsurance/programme'] },
      { icon: '📋', title: 'The loss',
        desc: 'Ransomware strikes: the insurer’s response panel runs the first 72 hours — forensics, legal, notification — then pays business interruption and any privacy claims. The product is a service as much as an indemnity.',
        links: ['classes2/cyber'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Incident costs settle quickly; privacy litigation takes longer. Renewal underwriting feeds back loss lessons as required controls — underwriting and loss prevention fused.',
        links: ['claims/ibnr'] }
    ]
  },
  {
    id: 'political-credit',
    icon: '🌍',
    name: 'Political risk & credit',
    intro: 'A bank’s protection on emerging-market lending — insurance competing with capital markets, underwritten like applied geopolitics.',
    stages: [
      { icon: '🌍', title: 'The client and the risk',
        desc: 'A bank finances commodity exports from a frontier market and wants protection against the buyer defaulting or the government blocking payment — credit and political perils intertwined.',
        links: ['classes2/political-credit'] },
      { icon: '🤝', title: 'The broking chain',
        desc: 'A specialist broker structures the deal: insured percentage (the bank retains a slice), waiting period, tenor matched to the loan — wordings negotiated against banking regulation.',
        links: ['bespoke/credit-enhancement'] },
      { icon: '✍️', title: 'Placement: syndication',
        desc: 'The lead underwrites obligor, country and structure; large deals syndicate across the small community of credit and political-risk markets — subscription reborn as deal syndication.',
        links: ['bespoke/deal-lifecycle'] },
      { icon: '💷', title: 'Premium',
        desc: 'Multi-year premium follows the loan’s life, often paid annually in advance; earning matches the exposure profile as the loan amortises.',
        links: ['premium/earning'] },
      { icon: '🌪️', title: 'Exposure management',
        desc: 'Aggregation runs by obligor and country, not postcode: one sovereign crisis or corporate collapse can hit dozens of policies. Country limits are the binding budget.',
        links: ['classes2/political-credit'] },
      { icon: '🏦', title: 'Capital',
        desc: 'Credit risks cluster in recessions — wrong-way risk — so diversification credit against catastrophe books is real, but against other credit exposures much less so.',
        links: ['bespoke/credit-enhancement'] },
      { icon: '🛡️', title: 'Outwards reinsurance',
        desc: 'Whole-account treaties protect the credit book; hybrid deals need careful checking that class-based treaty wordings actually pick them up.',
        links: ['bespoke/deal-lifecycle'] },
      { icon: '📋', title: 'The loss',
        desc: 'The buyer defaults amid a currency crisis. After the 180-day waiting period filters delay from default, the insurer pays its share — then spends years pursuing recoveries in the restructuring.',
        links: ['classes2/political-credit'] },
      { icon: '📊', title: 'Reserving, results and the cycle',
        desc: 'Ultimate cost depends on recoveries as much as the default itself: net loss ratios turn on restructuring skill. The class’s cycle follows the global credit cycle, not the hurricane season.',
        links: ['claims/ibnr'] }
    ]
  }
];
