/* Glossary — plain-English definitions of market terms and acronyms */
window.LMA_GLOSSARY = [
  { term: 'Aggregate exposure', def: 'The total amount an insurer could lose across all its policies from one peril in one zone (or one shared dependency). The unit of exposure management.' },
  { term: 'Aggregate limit', def: 'A cap on the total of all claims paid under a policy or treaty in a period, as opposed to a per-loss or per-event limit.' },
  { term: 'Attachment point', def: 'The loss level above which an excess-of-loss layer starts paying. In “£20m xs £5m”, the attachment is £5m.' },
  { term: 'Attritional losses', def: 'The frequent, small, statistically stable claims of everyday experience — as opposed to large single losses or catastrophes.' },
  { term: 'Average clause', def: 'A property policy clause reducing claim payments proportionally when the insured declared values below the true value (underinsurance).' },
  { term: 'Binding authority (binder)', def: 'A contract delegating authority to a coverholder to accept risks and issue documents on an insurer’s behalf within defined limits.' },
  { term: 'Bordereau (plural bordereaux)', def: 'A periodic report from a coverholder or cedant listing risks bound, premiums and claims under a delegated or reinsurance arrangement.' },
  { term: 'Bornhuetter–Ferguson method', def: 'A reserving method that adds actual claims to date to the unreported portion of an independent prior expectation — stabilising estimates for young, long-tail years.' },
  { term: 'Broker', def: 'The intermediary acting for the insurance buyer, structuring the risk and placing it with insurers. Nearly all London market business is broker-distributed.' },
  { term: 'Burning cost', def: 'A simple experience-based price: historical losses that would have hit a layer or policy, averaged per year (and properly adjusted for inflation and exposure changes).' },
  { term: 'Business interruption', def: 'Cover for lost profit and continuing costs while damaged operations are out of action. Often exceeds the physical damage loss itself.' },
  { term: 'Capacity', def: 'The amount of insurance limit a carrier (or the whole market) is able and willing to provide.' },
  { term: 'Case reserve', def: 'A claims handler’s estimate of the remaining cost of a specific known claim.' },
  { term: 'Catastrophe model', def: 'A simulation tool (hazard × exposure × vulnerability × financial terms) that estimates the probability distribution of losses from perils like hurricanes and earthquakes.' },
  { term: 'Cedant', def: 'An insurer that buys reinsurance, “ceding” part of its risk to a reinsurer.' },
  { term: 'Ceding commission', def: 'A payment from reinsurer to cedant under proportional reinsurance, compensating the cedant’s acquisition costs and expenses.' },
  { term: 'Central Fund', def: 'The mutual pool at Lloyd’s, financed by member levies, that pays valid claims if a member cannot — the final link in the chain of security.' },
  { term: 'Central settlement', def: 'The London market system netting all premium and claim movements between each broker and carrier into consolidated periodic payments per currency.' },
  { term: 'Chain ladder', def: 'The classic reserving method: measure how past claim cohorts developed over time, assume the pattern persists, and project ultimate claims for younger cohorts.' },
  { term: 'Claims-made policy', def: 'A liability policy triggered by claims first made against the insured during the policy period (with a retroactive date), typical of professional and financial lines.' },
  { term: 'Combined ratio', def: 'Loss ratio plus expense ratio. Below 100% means underwriting profit; above means underwriting loss (before investment income).' },
  { term: 'Coming into line', def: 'The twice-yearly Lloyd’s process where every member must show its Funds at Lloyd’s meet its capital requirement.' },
  { term: 'Consortium', def: 'An arrangement where several insurers pool capacity so one underwriter can write a combined, larger line on behalf of the group.' },
  { term: 'Constructive total loss', def: 'A marine loss where repair would cost more than the insured value, so the insured abandons the property and claims the full insured value.' },
  { term: 'Contractual service margin', def: 'Under the 2023 international accounting standard (IFRS 17), the unearned profit in insurance contracts, recognised gradually as cover is provided.' },
  { term: 'Control of well', def: 'Upstream energy cover for the costs of regaining control of a well blowout — well kill, redrilling, cleanup. Also called operators’ extra expense.' },
  { term: 'Coverholder', def: 'A company authorised under a binding authority to accept risks on an insurer’s behalf — the delegated “pen”.' },
  { term: 'Deductible (excess, retention)', def: 'The first portion of each loss retained by the insured before insurance responds.' },
  { term: 'Delegated authority', def: 'The umbrella term for business where underwriting decisions are delegated to third parties (coverholders, managing general agents) under binders.' },
  { term: 'Development triangle', def: 'Claims data arranged by origin year (rows) and age (columns), showing how cohorts of claims grow over time — the raw material of reserving.' },
  { term: 'Diversification benefit', def: 'The reduction in total capital needed because different risks are unlikely to go wrong simultaneously; the whole requires less than the sum of the parts.' },
  { term: 'D&F (direct & facultative)', def: 'The open-market property class: large individual property risks written directly or as facultative reinsurance, rather than through treaties or binders.' },
  { term: 'D&O (directors’ & officers’ liability)', def: 'Cover protecting company directors and officers personally against claims alleging mismanagement of the company.' },
  { term: 'E&O (errors & omissions)', def: 'Another name for professional indemnity — liability cover for negligent professional services or advice.' },
  { term: 'Earned premium', def: 'The portion of written premium corresponding to cover already provided. Performance is judged on earned premium versus incurred claims.' },
  { term: 'ECA (Economic Capital Assessment)', def: 'The capital a Lloyd’s member must hold: the syndicate’s ultimate one-in-200 requirement plus a 35% economic uplift.' },
  { term: 'Excess of loss', def: 'Non-proportional reinsurance paying only the part of a loss (or event, or annual aggregate) above an attachment point, up to a limit.' },
  { term: 'Exceedance-probability curve', def: 'A catastrophe model output showing, for each loss size, the annual probability that losses exceed it — read at return periods like 1-in-100.' },
  { term: 'Exposure rating', def: 'Pricing from the characteristics of the risk (values, construction, jurisdiction) using market-wide data and models, rather than the risk’s own claims history.' },
  { term: 'Facultative reinsurance', def: 'Reinsurance of one specific individual risk, offered and accepted case by case — as opposed to treaty reinsurance of a whole portfolio.' },
  { term: 'Funds at Lloyd’s', def: 'Assets a member lodges in trust at Lloyd’s to support its underwriting — the second link in the chain of security.' },
  { term: 'General average', def: 'The ancient marine principle that all parties to a voyage contribute proportionally to sacrifices made to save it (jettison, salvage).' },
  { term: 'Gross written premium', def: 'The full contract price of insurance before deductions — brokerage, commissions, taxes — and before outwards reinsurance.' },
  { term: 'Hard market / soft market', def: 'Phases of the underwriting cycle: rising prices and tight terms after capital withdraws (hard); falling prices and loose terms as capital floods in (soft).' },
  { term: 'Hours clause', def: 'A reinsurance clause defining the maximum time span of losses that count as a single event — critical for per-event recoveries in long-running disasters.' },
  { term: 'IBNR (incurred but not reported)', def: 'Reserves for losses that have happened but not yet been reported to the insurer — plus, in practice, expected development on known claims. The bulk of long-tail reserves.' },
  { term: 'Incurred claims', def: 'Paid claims plus outstanding case reserves (and in some uses, plus IBNR). “Incurred to date” usually means paid plus case reserves.' },
  { term: 'International Underwriting Association', def: 'The trade body for the London company (non-Lloyd’s) insurance and reinsurance market.' },
  { term: 'Lead underwriter', def: 'The insurer who negotiates terms and price for a subscription placement and writes the first line, which following insurers subscribe behind.' },
  { term: 'Line', def: 'An insurer’s percentage share of a risk. Also, on a surplus treaty, the cedant’s retention amount used as the unit of treaty capacity.' },
  { term: 'Lineslip', def: 'A standing facility where a group of insurers pre-agrees to consider risks of a defined type from a specific broker, with the lead approving each risk.' },
  { term: 'Lloyd’s of London', def: 'The insurance marketplace (not itself an insurer) where syndicates backed by members underwrite, overseen by the Corporation of Lloyd’s.' },
  { term: 'Loss adjuster', def: 'An independent expert appointed to investigate and quantify a loss.' },
  { term: 'Loss ratio', def: 'Incurred claims divided by earned premium — the core measure of claims experience.' },
  { term: 'Managing agent', def: 'The company that runs one or more Lloyd’s syndicates: employs underwriters and staff, accountable to Lloyd’s.' },
  { term: 'Managing general agent', def: 'A large, sophisticated coverholder — an underwriting business writing on other insurers’ capital under delegated authority.' },
  { term: 'Market Reform Contract', def: 'The standardised London market contract document — the modern successor to the paper slip.' },
  { term: 'Minimum and deposit premium', def: 'A structure where a deposit premium is paid up front and adjusted upward if actual exposure exceeds estimates — but never below the minimum.' },
  { term: 'Names', def: 'The traditional individual members of Lloyd’s whose personal wealth backed syndicates; today capital is mostly corporate.' },
  { term: 'Net written premium', def: 'Usually: gross written premium minus outwards reinsurance premium. “Net” can also mean net of brokerage — always check which.' },
  { term: 'Occurrence policy', def: 'A liability policy triggered by injury or damage happening during the policy period, whenever the claim is eventually made — the source of decades-long tails.' },
  { term: 'Order', def: 'The share of a whole risk the client asks to be placed in a market (e.g. a 75% order to London, the rest placed locally).' },
  { term: 'P&I club (protection & indemnity)', def: 'A mutual insurer owned by shipowners covering their liabilities (crew, pollution, wreck removal), reinsured collectively into the market.' },
  { term: 'Parametric insurance', def: 'Cover paying a set amount when an objective index (wind speed, rainfall) crosses a trigger — fast and certain, but with basis risk versus actual loss.' },
  { term: 'Payback period', def: 'Limit divided by premium: how many years of premium a full-limit loss consumes. The reciprocal of rate on line.' },
  { term: 'Political violence insurance', def: 'Cover for damage from terrorism through to riots, insurrection and war on land.' },
  { term: 'Pool Re', def: 'The United Kingdom’s government-backed mutual reinsurer for terrorism losses above member insurers’ retentions.' },
  { term: 'PPL (Placing Platform Limited)', def: 'The London market’s electronic placing platform, where most risks are now negotiated and bound.' },
  { term: 'Premium trust fund', def: 'The trust in which Lloyd’s premiums are held for policyholders’ benefit; profits release only after a year of account closes.' },
  { term: 'Probable maximum loss', def: 'A realistic estimate of the worst plausible loss on a risk or zone — as opposed to the theoretical total insured value.' },
  { term: 'Profit commission', def: 'A share of profit returned by a reinsurer to a cedant (or insurer to coverholder) when an account performs well.' },
  { term: 'Proportional reinsurance', def: 'Reinsurance sharing premiums and losses in a defined ratio (quota share, surplus), usually with a ceding commission.' },
  { term: 'Quota share', def: 'Proportional reinsurance ceding a fixed percentage of every policy in a class — premiums and losses alike.' },
  { term: 'Rate change', def: 'The price movement on renewing business adjusted to constant exposure and cover — the honest measure of pricing progress, unlike raw premium change.' },
  { term: 'Rate on line', def: 'Premium divided by limit for an excess-of-loss layer — the fraction of the amount at stake charged per year.' },
  { term: 'RDS (realistic disaster scenarios)', def: 'The prescribed set of mega-event stress tests every Lloyd’s syndicate must estimate losses for, gross and net of reinsurance.' },
  { term: 'Reinstatement', def: 'Restoring an exhausted reinsurance layer’s limit after a loss, usually for an additional (often pro rata) reinstatement premium.' },
  { term: 'Reinsurance to close (RITC)', def: 'The transaction closing a Lloyd’s year of account: all remaining liabilities transfer to the next year for a premium equal to their estimated value.' },
  { term: 'Reserve release / strengthening', def: 'Revising prior-year claim estimates down (adding to profit) or up (creating losses). Persistent strengthening signals systematic under-reserving.' },
  { term: 'Retention', def: 'The amount of risk kept net by an insurer (or insured) rather than transferred — per risk, per event, or in aggregate.' },
  { term: 'Retrocession', def: 'Reinsurance bought by reinsurers to protect their own portfolios — the top of the risk-transfer chain.' },
  { term: 'Return on capital', def: 'Profit divided by the capital allocated to support the business — the key measure for comparing classes and justifying reinsurance.' },
  { term: 'Return period', def: 'The inverse of annual exceedance probability: a “1-in-100-year” loss has a 1% chance of being exceeded in any year (not a schedule!).' },
  { term: 'Risk margin / risk adjustment', def: 'An addition to best-estimate liabilities representing compensation for bearing uncertainty, required under solvency and accounting standards.' },
  { term: 'SCR (Solvency Capital Requirement)', def: 'The regulatory capital requirement: enough capital to survive a one-in-200-year loss over one year.' },
  { term: 'Signed line', def: 'An insurer’s final share of a risk after oversubscribed written lines are proportionally reduced to total 100%. Premium and claims follow the signed line.' },
  { term: 'Signing down', def: 'The proportional reduction of written lines when a placement is oversubscribed beyond 100%.' },
  { term: 'Silent cyber', def: 'Cyber-caused losses covered unintentionally under policies not designed or priced for cyber — now addressed by mandatory affirmation or exclusion.' },
  { term: 'Slip', def: 'The (historically paper) document recording a risk’s terms and each insurer’s line — today the electronic Market Reform Contract.' },
  { term: 'Social inflation', def: 'Growth in liability claim costs beyond economic inflation, driven by litigation trends, jury awards and litigation funding.' },
  { term: 'Stop loss', def: 'Reinsurance protecting an annual result: pays when aggregate losses or the loss ratio for a period exceed a threshold.' },
  { term: 'Subscription market', def: 'A market where several insurers each take shares of the same risk on the same slip — the defining London structure.' },
  { term: 'Surplus treaty', def: 'Proportional reinsurance where the cedant retains a fixed monetary line per risk and cedes the surplus above it, so the ceded percentage varies by risk size.' },
  { term: 'Syndicate', def: 'A Lloyd’s underwriting venture, identified by number, through which members accept risk; run by a managing agent.' },
  { term: 'Tail (short/long)', def: 'How long claims take to be reported and settled after the policy period. Property is short-tail; liability is long-tail.' },
  { term: 'Technical provisions', def: 'The balance-sheet value of insurance obligations: discounted best-estimate liabilities plus a risk margin.' },
  { term: 'Total insured value', def: 'The sum of insured limits/values exposed — the theoretical maximum loss if everything is destroyed.' },
  { term: 'Treaty reinsurance', def: 'Reinsurance covering a whole portfolio of risks automatically, negotiated once — as opposed to facultative (risk-by-risk).' },
  { term: 'Underwriting cycle', def: 'The multi-year alternation of hard and soft markets driven by capital flows and the delay in learning the true cost of business.' },
  { term: 'Unearned premium', def: 'Written premium for cover not yet provided — held as a liability until it is earned.' },
  { term: 'Velonetic', def: 'The operator of the London market’s central processing bureau (formerly Xchanging), which checks, signs and settles market transactions.' },
  { term: 'Written line', def: 'The share of a risk an underwriter originally commits to on the slip — before any signing down.' },
  { term: 'Written premium', def: 'Premium recognised when a contract is bound — the full contract price, regardless of how much cover has yet been provided.' },
  { term: 'Year of account', def: 'The Lloyd’s accounting year to which a policy belongs (by inception date), whose capital providers take the resulting profit or loss.' },
  { term: 'Adverse development cover', def: 'Retrospective reinsurance attaching at (or near) booked reserves, protecting against prior-year claims deterioration up to a limit — excess of loss on reserves.' },
  { term: 'Basis risk', def: 'The mismatch between an index-based payout (parametric or industry-loss trigger) and the buyer’s actual loss — cover can pay too little, too much, or not at all.' },
  { term: 'Broker facility', def: 'A pre-arranged commitment of follow capacity to a share of qualifying risks a broker places, usually in exchange for enhanced commission.' },
  { term: 'Catastrophe bond', def: 'A security whose investors lose principal (held in a collateral trust) if a defined catastrophe occurs, providing the sponsor with pre-funded, credit-risk-free protection.' },
  { term: 'Consortium fee / commission override', def: 'Payment a consortium leader or capacity manager earns from followers for underwriting on behalf of their combined capacity.' },
  { term: 'Deficit carry-forward', def: 'A profit-commission clause requiring past losses to be recouped before profit share is payable again — a key alignment tool in delegated and framework arrangements.' },
  { term: 'Framework agreement', def: 'The long-term contract between a managing general underwriter and its balance-sheet carrier(s), governing delegated classes, guidelines, data rights and economics.' },
  { term: 'Fronting', def: 'A licensed, rated insurer issuing policies and reinsuring most or all of the risk to the capital that actually wants it (a captive, fund or unrated reinsurer), for a fronting fee — while remaining fully liable to policyholders.' },
  { term: 'Loss portfolio transfer', def: 'A retrospective transaction transferring booked reserves for past business to a (legacy) reinsurer for a premium approximately equal to their discounted value.' },
  { term: 'Managing general underwriter (MGU)', def: 'A full-scale underwriting business writing on other carriers’ paper under framework agreements — paid by commissions and profit share rather than holding risk capital.' },
  { term: 'Profit commission (framework)', def: 'A share of underwriting profit paid by a carrier to the underwriting business that produced it, usually above a threshold and often with deficit carry-forward.' },
  { term: 'Sidecar', def: 'A collateralised special-purpose vehicle through which investors take a quota share of a sponsor’s book for a period, with the sponsor typically earning fees and profit overrides.' },
  { term: 'Significant risk transfer', def: 'Structures (recognised by banking regulators) in which insurers or funds protect tranches of bank loan portfolios, reducing the bank’s regulatory capital.' },
  { term: 'Smart follower', def: 'A carrier or vehicle that follows chosen leads systematically (by rule or algorithm) with a minimal cost base, competing on expense ratio rather than risk selection.' },
  { term: 'Tax liability insurance', def: 'Cover for a specific, identified tax position failing on challenge — underwritten from legal opinions; a known-risk transactional product.' },
  { term: 'Trapped collateral', def: 'Collateral held in trust against potential loss development after an event, unavailable to investors for redeployment — a drag that slows alternative capital’s return after catastrophes.' },
  { term: 'Warranty & indemnity insurance', def: 'Cover paying a company buyer for breaches of the seller’s warranties discovered after completion (in the United States: representations & warranties insurance).' }
];
window.LMA_GLOSSARY.sort(function (a, b) { return a.term.localeCompare(b.term); });
